### PR TITLE
Add Dropdown Layout

### PR DESCRIPTION
**Pull request by jburgess**
This adds support for the following enhancements:

* TImepicker can now display items in a Dropdown List (https://github.com/WilliamVenner/grafana-timepicker-buttons/issues/6)
* Button orientation can be configured to display buttons either horizontally or vertically.
* Utilization of _Grafana_ styles and form controls.

### CODE REVIEW

**Comment by WilliamVenner** [comment]
Thank you jburgess, fantastic PR.

**Comment by jburgess** [comment]
Thanks @WilliamVenner. Appreciate the merge! Do you know when this will be available in the main _Grafana_ plug-in repo?

**Comment by WilliamVenner** [comment]
They can be pretty slow. They manually test everything, including updates I believe. I have to make a PR to submit an update to the Grafana plugin repo.

**Comment by WilliamVenner** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/872

**Pull request merged**
